config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope '(:locale)', locale: /en|pt-BR/ do

    resources :hangouts do
      member do
        get "share"
        patch "launch_vote"
        patch "cancel_hg"
        patch "close_vote"
        patch "submit_vote"
        get "submit_vote"
      end
      resources :confirmations, only: [:new, :create, :edit, :update, :destroy] do
      end
      

    end

    get 'profiles/show'

    root to: 'hangouts#new'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
    @user = current_user
    authorize @user
    @hangouts_as_host = @user.hangouts

    @confirmations_as_guest = []
    @user.confirmations.each do |conf|
      if conf.hangout.user != @user
        @confirmations_as_guest << conf
      end
    @confirmations_as_guest
    end
  end



end
        #Hangout.where("DATE(date) < ?", '2018-04-26')

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/show.html.erb
<div class="header center-align vertical-align">
  <%= image_tag @user.facebook_picture_url, class: 'circle'%>
  <h4 class="white-text"> <%= @user.first_name %> <%= @user.last_name %></h4>

</div>
<h4 class="center-align padded-top-1"> <%= t('.title') %></h4>
  <ul class="collapsible center-align " data-collapsible="accordion">
    <li>
      <div class="collapsible-header padded-small"  id="open_delay">
        <h5><%= t('.host-collapse') %> </h5>
      </div>
          <div class="collapsible-body padded-small">
          <% if @user.hangouts.future_hangout(Time.zone.now).valid.size == 0 %>
            <p ><%= t('.host_zero_event') %> </p>
          <% else %>
            <%@user.hangouts.order(date: :asc).future_hangout(Time.zone.now).valid.each do |hangout|%>
            <p id="list_profile"><%= t('.host_list_html', link: link_to(hangout.title, hangout_path(hangout))) %></p>
            <p><%= l hangout.date, format: :short %></p>
            <div class=" valign-wrapper center-align" style="justify-content: center;">
              <% if Confirmation.where( hangout: hangout, user: @user)[0].nil? %>
                <%= button_to t('.button_set_location'), hangout_path(hangout), method: :get, class: "btn-small" %>
              <% elsif hangout.status == "confirmations_on_going" %>
                <%= button_to t('.button_launch_vote'), launch_vote_hangout_path(hangout), method: :patch, class: "btn-small" %>
              <% elsif hangout.status == "vote_on_going" %>
                <%= button_to t('.button_final_vote'), close_vote_hangout_path(hangout), method: :patch, class: "btn-small" %>
              <% else %>
                <%= button_to t('.vote_closed'), hangout_path(hangout), method: :get, class: "btn-small green lighten-1" %>
              <% end %>

            <%= link_to edit_hangout_path(hangout), class: "btn-small lighten-1" do %>
              <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
            <% end %>
            <%= button_to cancel_hg_hangout_path(hangout),class:"btn-small red lighten-1", method: :patch, data: { confirm: t('.alert_delete') } do %>
              <i class="fa fa-trash-o" aria-hidden="true"></i>
            <% end %>
            </div>
            <hr class="grey lighten-2">
          <% end %>
        </div>
      <% end %>
    </li>
    <li>
      <div class="collapsible-header padded-small">
        <h5><%= t('.guest-collapse') %> </h5>
      </div>
        <div class="collapsible-body padded-small">
          <% if @user.hangouts_as_guest.future_hangout(Time.zone.now).valid.size == 0 %>
            <p ><%= t('.guest_zero_event') %> </p>
          <% else %>
          <%@user.hangouts_as_guest.order(date: :asc).future_hangout(Time.zone.now).valid.each do |hangout|%>
        <p id="list_profile"><%= t('.guest_list_html', link: link_to(hangout.title, hangout_path(hangout)), host: hangout.user.first_name ) %></p>
        <p><%= l hangout.date, format: :short %></p>
        <div class=" valign-wrapper center-align" style="justify-content: center;">
          <% if hangout.status == "vote_on_going" %>
                <%= button_to t('.vote_started'), hangout_path(hangout), method: :get, class: "btn-small" %>
              <% elsif hangout.status == "result" %>
                <%= button_to t('.vote_closed'), hangout_path(hangout), method: :get, class: "btn-small" %>
              <% else %>
                <%= button_to t('.waiting'), hangout_path(hangout), method: :get, class: "btn-small grey lighten-1" %>
            <% end %>

        <%= button_to hangout_confirmation_path( hangout, Confirmation.where( hangout: hangout, user: current_user)[0].id) , :method=> :delete, class:"btn-small grey lighten-1", data: { confirm: t('.alert_delete') } do %><i class="fa fa-trash-o" aria-hidden="true"></i>
            <% end %>
          </div>
        <% end %>
        </div>
      <% end %>
    </li>
  </ul>
  <% content_for :after_js do %>
    <script>
    $(document).ready(function(){
          setTimeout(function(){
             $("#open_delay").trigger( "click" );
         }, 1500);
    });
  </script>
<% end %>