config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope '(:locale)', locale: /en|pt-BR/ do

    resources :hangouts do
      member do
        get "share"
        patch "launch_vote"
        patch "cancel_hg"
        patch "close_vote"
        patch "submit_vote"
        get "submit_vote"
      end
      resources :confirmations, only: [:new, :create, :edit, :update, :destroy] do
      end
      

    end

    get 'profiles/show'

    root to: 'hangouts#new'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% content_for :after_js do %>
<% if notice %>
  <script type="text/javascript">
    Materialize.toast('<%= notice %>', 3000)
  </script>
<% end %>
<% if alert %>
  <script type="text/javascript">
    Materialize.toast('<%= alert %>', 3000)
  </script>
<% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="center-align  on-top-of-map">
  <div class="valign-wrapper">
    <div class="container">
      © 2017 made with <i class="fa fa-heart" aria-hidden="true"></i> at le wagon.
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="on-top-of-map">
  <div class="nav-wrapper">
    <%= link_to root_path do %>
      <a href="#" class="brand-logo center"><spam class="deep-orange-text">k</spam>ippis</a>
    <% end %>
    <a href="root_path" data-activates="mobile-demo" class="button-collapse show-on-large">
      <i class="material-icons">menu</i>
    </a>
  <% unless current_user.nil? %>
    <ul class="side-nav" id="mobile-demo">
      <div class="avatar-navbar-wrapper center-align vertical-align">
        <%= image_tag current_user.facebook_picture_url, class: 'circle' %>
        <h4><%= current_user.first_name %> <%= current_user.last_name %></h4>
      </div>
      <li><%= link_to root_path do %>
        <i class="material-icons">mood</i><%= t(".hangout-create", default: "New Hangout") %>
      <% end %>
      </li>
      <li><%= link_to profiles_show_path do %>
        <i class="material-icons">person</i><%= t(".profile", default: "Profile") %>
      <% end %>
      </li>
      <li><%= link_to destroy_user_session_path, method: :delete do %>
        <i class="material-icons">exit_to_app</i><%= t(".sign_out", default: "Log out") %>
      <% end %>
      </li>
      </ul>
    <% else %>
    <ul class="side-nav" id="mobile-demo">

      <li><%= link_to user_facebook_omniauth_authorize_path, class:'btn z-depth-2', id: 'facebook-btn-sidenav' do %>
        <i class="fa fa-facebook-official fa-2x" id="face-icon" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;Log in With Facebook
      <% end %></li>
    </ul>
    <% end %>
  </div>
</nav>