config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope '(:locale)', locale: /en|pt-BR/ do

    resources :hangouts do
      member do
        get "share"
        patch "launch_vote"
        patch "cancel_hg"
        patch "close_vote"
        patch "submit_vote"
        get "submit_vote"
      end
      resources :confirmations, only: [:new, :create, :edit, :update, :destroy] do
      end
      

    end

    get 'profiles/show'

    root to: 'hangouts#new'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hangout.rb
class Hangout < ApplicationRecord
  belongs_to :user
  belongs_to :place, optional: true
  has_many :confirmations
  has_many :place_options

  validates :title, presence: true, length: { maximum: 60, message: "Maximum 60 characters" }
  validates :date, presence: true, inclusion: { in: (Date.today..Date.today+10.years), message: "Can not be in the past" }
  validates :category, presence: true
  validates :status, presence: true


  scope :cancelled, -> { where(status: "cancelled") }
  scope :valid, -> { where.not(status: "cancelled") }
  scope :vote_now, -> { where(status: "vote_on_going") }
  scope :vote_finished, -> { where(status: "result") }
  scope :past_hangout, ->(time) { where("date < ?", time) }
  scope :future_hangout, ->(time) { where("date > ?", time) }


  geocoded_by :center_address
  after_validation :geocode, if: :center_address?

end

app/controllers/hangouts_controller.rb
  class HangoutsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:create, :new, :show]

  before_action :set_hangout, only: [:show, :share, :edit, :update, :cancel_hg, :launch_vote, :submit_vote, :has_voted?,:close_vote]

  def new
    @hangout = Hangout.new(session.fetch(:hangout, {}).fetch("hangout", nil))
    authorize @hangout
  end

  def index
    @hangouts = policy_scope(Hangout)
  end

  def create
    if current_user.nil?
      session[:hangout] = params
      @hangout = Hangout.new(hangout_params)
      authorize @hangout

      if valid_param?(@hangout)
        #  redirect_to new_user_session_path
        redirect_to user_facebook_omniauth_authorize_path
      else
        render :new and return
      end

    else
      @hangout = Hangout.new(hangout_params)
      # @hangout.date = Time.parse(@hangout.date)
      authorize @hangout
      @hangout.status = "confirmations_on_going"
      @hangout.user = current_user

        # session[:hangout] = nil
      if @hangout.optimize_location == false
        @hangout.adj_latitude = @hangout.latitude
        @hangout.adj_longitude = @hangout.longitude
        @hangout.radius = 600
      end
      if @hangout.save
      HangoutMailer.creation_confirmation(@hangout).deliver_now    ####   mail
      redirect_to new_hangout_confirmation_path(@hangout)
      flash[:notice] = "Hangout criado com sucesso!"
      else
        render :new
      end
    end
  end

  def show
    #Render router:
    hg_confirmations = @hangout.confirmations.map {|x| x.user}
    if (@hangout.date + 6 * 60 * 60) > Time.now #add 6hours in order not to put the hg in past right away
      if current_user.nil?
        @render = 'invitation'
      else
        if hg_confirmations.include?(current_user)  #checking if current user has already a confirmation for this HG
          hangoutshow_by_status
        else
          @render = 'invitation'
        end
      end
    else
      @render = 'past'
    end
  end

  def submit_vote
    place = Place.find(params[:place_id])
    confirmation.place = place
    authorize @hangout
    @confirmation.save
    redirect_to hangout_path(@hangout)
    flash[:notice] = "Voto realizado com sucesso!"
  end

  def has_voted?
    confirmation.place.present?
  end
  helper_method :has_voted?

  def place_list
    @hangout.place_options
  end
  helper_method :place_list

  def voted_place
    confirmation.place
  end
  helper_method :voted_place

  def launch_vote
    # Call PlacesAPI to create place_options
    initialize_places_api
    @hangout.status = "vote_on_going"
    @hangout.save
    @hangout.confirmations.each do |confirmation|
      if confirmation.user != @hangout.user
        HangoutMailer.vote_starting(confirmation).deliver_now ####   mail
      end
    end
    redirect_to hangout_path(@hangout)
    #Send notifications
  end

  def edit
  end

  def update
    @hangout.update_attributes(hangout_params)
    #launch_vote_hangout_path(@hangout)
    HangoutMailer.update_confirmation(@hangout).deliver_now
    @hangout.confirmations.each do |confirmation|
      if confirmation.user != @hangout.user
        HangoutMailer.hangout_update(confirmation).deliver_now ####   mail
      end
    end
    redirect_to hangout_path(@hangout)
    flash[:notice] = "Hangout editado!"
    #Send notifications
  end

  def cancel_hg
    @hangout.status = "cancelled"
    @hangout.save
    @hangout.confirmations.each do |confirmation|
      if confirmation.user != @hangout.user
        HangoutMailer.cancelled(confirmation).deliver_now ####   mail
      end
    end
    redirect_to profiles_show_path
    flash[:notice] = "Hangout cancelado!"
  end

  def close_vote
    votes = []
    @hangout.confirmations.each do |conf|
      if conf.place
       votes << conf.place
      end
    end
    counts = Hash.new 0
    votes.each do |place|
      counts[place] += 1
    end
    higher_vote = counts.max_by{|k,v| v}[1] #higher vote number
      if counts.select { |key, value| value == higher_vote }.size > 1 #check whether more than one places as the highest vote number
        places = counts.select { |key, value| value == higher_vote }.keys # array with winners
        places_rating = Hash.new 0
          places.each do |place|
          places_rating[place] = place.rating
        end
        higher_rating = places_rating.max_by{|k,v| v}[1]
        if places_rating.select { |key, value| value == higher_rating }.size > 1 #higher vote number
          choice = places_rating.select { |key, value| value == higher_rating }.keys
          winner = choice.sample
        else
          winner = places_rating.max_by{|k,v| v}[0]
        end
      else
        winner = counts.max_by{|k,v| v}[0]
      end
    @hangout.place = winner
    @hangout.status = "result"
    @hangout.save!

    winner_coord = {lat: winner.latitude, lng: winner.longitude}
    #update travel time and distance
    @hangout.confirmations.each do |confirmation|
      get_direction(confirmation, winner_coord, @hangout.date)
    end

    @hangout.confirmations.each do |confirmation|
      if confirmation.user != @hangout.user
        HangoutMailer.result(confirmation).deliver_now ####   mail
      end
    end
    redirect_to hangout_path(@hangout)
  end

  def share
  end

private

  def hangout_params
    params.require(:hangout).permit(:title, :date, :category, :center_address, :status, :optimize_location, :center_address, :latitude, :longitude)
  end

  def set_hangout
    @hangout = Hangout.find(params[:id])
    authorize @hangout
  end

  def confirmation
    @confirmation ||= Confirmation.find_by(user: @current_user, hangout: @hangout)
  end

  def hangoutshow_by_status
    if @hangout.status == "confirmations_on_going"
      @render = 'confirmationfollowup'
      @confirmations = Confirmation.all.where('hangout_id = ?',@hangout.id)
      @confirmation_markers = []
        @confirmations.each do |confirmation|
          @confirmation_markers << {lat: confirmation.latitude, lng: confirmation.longitude}
        end

      @center = {lat: @hangout.latitude, lng: @hangout.longitude}
      @adj_center = {lat: @hangout.adj_latitude, lng: @hangout.adj_longitude}
      @hangout.radius? ? @radius = @hangout.radius : @radius = 1  #necessary so that javascript can be compiled with radius nil
    elsif @hangout.status == "vote_on_going"
      @render = 'vote_option'
      @nb_conf = @hangout.confirmations.count
      @nb_vote = @hangout.confirmations.reduce(0) {|sum,conf| conf.place_id.nil? ? sum : sum  += 1}
    elsif @hangout.status == "result"
      @render = 'result'
      #confirmation
      @confirmations = Confirmation.all.where('hangout_id = ?',@hangout.id)

      @transport = confirmation.transportation
      @confirmation.time_to_place.nil? ? @leaving_time = 0 : @leaving_time = (@hangout.date - @confirmation.time_to_place)

      @departure = {lat: @confirmation.latitude, lng: @confirmation.longitude, address: @confirmation.leaving_address}
      @direction = {lat: @hangout.place.latitude, lng: @hangout.place.longitude, address: @hangout.place.address}
      @google_url = "//www.google.com/maps/dir/#{@departure[:lat]},#{@departure[:lng]}/#{@direction[:lat]},#{@direction[:lng]}"
#      @uber_url = "//m.uber.com/ul/?action=setPickup&client_id=BPnTmYM3BWbe7xQhQ7ATVyCcjWAx6HfJ&pickup=my_location&dropoff[latitude]=#{@direction[:lat]}&dropoff[longitude]=#{@direction[:lng]}', target: 'blank'%>"
      @uber_url = "//m.uber.com/ul/?action=setPickup&client_id=BPnTmYM3BWbe7xQhQ7ATVyCcjWAx6HfJ&pickup=my_location&dropoff[latitude]=#{@direction[:lat]}&dropoff[longitude]=#{@direction[:lng]}&dropoff[formatted_address]=#{@direction[:address]}"
      @taxi_url = "taxis99://call?"
#      @taxi_url = "taxis99://call?endLat=#{@direction[:lat]}&endLng=#{@direction[:lng]}&endName=#{@direction[:address]}"
    elsif @hangout.status == "cancelled"
      @render = 'cancelled'
    end
  end

  def initialize_places_api
    fetch = PlacesApi.new(@hangout)
    venues = fetch.fetch_places
    fetch.find_places(venues)
  end

  def get_direction(confirmation, destination, departure_time)
    url = "https://maps.googleapis.com/maps/api/distancematrix/json?units=metric&origins=#{confirmation.latitude},#{confirmation.longitude}&destinations=#{destination[:lat]},#{destination[:lng]}&departure_time=#{departure_time.to_i}&mode=#{confirmation.transportation.downcase}&key=#{ENV['GOOGLE_API_SERVER_KEY']}"
    url.gsub!('"')
    direction = RestClient.get url
    direction_info = JSON.parse(direction)
    confirmation.distance_to_place = direction_info["rows"][0]["elements"][0]["distance"]["value"]
    if confirmation.transportation == 'DRIVING'
      confirmation.time_to_place = direction_info["rows"][0]["elements"][0]["duration_in_traffic"]["value"]
    else
      confirmation.time_to_place = direction_info["rows"][0]["elements"][0]["duration"]["value"]
    end
    authorize confirmation
    confirmation.save
    return confirmation
  end


  def valid_param?(hangout)
    unless hangout.title.nil?
      if (hangout.title.length < 61) && (hangout.title.length> 0)
        a = true
      end
    end
    unless hangout.date.nil?
      if hangout.date > Time.now
        b = true
      end
    end
    unless hangout.category.nil?
      if hangout.category.length > 0
        c = true
      end
    end
    return a && b && c
  end
end

app/helpers/hangouts_helper.rb
module HangoutsHelper
end

app/views/hangouts/_cancelled.html.erb
<div class="header center-align">
  <%= image_tag @hangout.user.facebook_picture_url, class: 'circle z-depth-2'%>
    <h4 class="white-text"><%=@hangout.title%></h4>
    <p class="white-text"><%= l @hangout.date, format: :short %></p>
</div>
<div class="status-wrapper red">
  <p class="white-text center-align"><%= t('.status') %></p>
</div>
<div class="container">
  <div class="row padded-top-1">
    <div class="col s12 m6 l8  offset-m3 offset-l2 center-align">
      <h1><i class="large material-icons">mood_bad</i></h1>
      <h5><%= t('.content', user_name: @current_user.first_name, host_name:@hangout.user.first_name, hangout_title: @hangout.title) %></h5>
    </div>
  </div>
    <div class="row padded-top-1">
      <div class="col s12 m6 l8  offset-m3 offset-l2 center-align">
        <%= link_to t('.content-new'), root_path, class:'btn' %>
      </div>
    </div>
  </div>

app/views/hangouts/_confirmationfollowup.html.erb
<div class="header center-align">
  <%= image_tag @hangout.user.facebook_picture_url, class: 'circle z-depth-2'%>
    <h4 class="white-text"><%=@hangout.title%></h4>
    <p class="white-text"><%= l @hangout.date, format: :short %></p>
</div>
<div class="status-wrapper">
  <p class="white-text center-align"><%= t('.status') %></p>
</div>

<div id="map" style="width: 100%; height: 230px;"></div>

<div class="row">
  <ul class="collapsible collapsible-li center-align z-depth-1" data-collapsible="expandable">
    <li>
      <div class="collapsible-header active">  <%= image_tag current_user.facebook_picture_url, class: 'circle user z-depth-2' %><br><h5><%= "#{current_user.first_name} #{current_user.last_name}" %></h5></div>
      <div class="collapsible-body">
        <% unless @hangout.user == current_user %>
          <%= button_to t('.button_cancel'), share_hangout_path(@hangout), method: :get, class: "btn-small" %>
        <% else %>
        <p>Inicie a votação quando quiser ou convide mais amigos</p>
        <div class="valign-wrapper orange-text accent-4" style="justify-content: center;">
            <%= button_to t('.button_launch_vote'), launch_vote_hangout_path(@hangout), method: :patch, class: "btn-small" %>
          <%= button_to share_hangout_path(@hangout), method: :get, class: "btn-small green lighten-1" do %>
          <i class="material-icons">share</i><% end %>
          <%= button_to edit_hangout_path(@hangout),method: :get, class: "btn-small grey lighten-1" do %>
            <i class="material-icons">mode_edit</i>
          <% end %>
          <%= button_to cancel_hg_hangout_path(@hangout),class: "btn-small grey lighten-1", method: :patch, data: { confirm: t('.alert_delete') } do %><i class="material-icons">delete</i><% end %>
        <% end %>
      </div>
    </li>
    <li>
      <div class="collapsible-header active"><h5><%= t('.guest-collapse') %></h5></div>
      <div class="collapsible-body">
        <ul>
          <div class="row">
            <div class="col s12">
              <% @confirmations.each do |confirmation| %>
              <div class="col s3 m1 l1"><li><%= image_tag confirmation.user.facebook_picture_url, class: "circle tooltipped", data: { position: "top", delay: "50", tooltip: "#{confirmation.user.first_name}"}%></li></div>
              <%end%>
            </div>
          </div>
        </ul>
      </div>
    </div>
    </li>
  </ul>
</div>



<% content_for(:after_js) do %>
  <script type="text/javascript">
    Materialize.toast("<%= t('.toast') %>", 3000);
  </script>

  <%= javascript_tag do %>

    $(document).ready(function initMap() {
      console.log('HELLO')
      var markers = (<%= raw @confirmation_markers.to_json %>);
      var bounds = new google.maps.LatLngBounds();

      markers.forEach(function(marker) {
        var marker = new google.maps.Marker({
          position: {lat: marker.lat, lng: marker.lng},
          map: map,
        });
      bounds.extend(marker.position);
      });

      console.log(<%= @confirmation_markers.count%>)

      if ( <%= @confirmation_markers.count%> > 1) {
        map.fitBounds(bounds);
      //  var center = (<%= raw @center.to_json %>);
      //  var cityCircle = new google.maps.Circle({
      //    strokeColor: '#FF0000',
      //    strokeOpacity: 0.8,
      //    strokeWeight: 2,
      //    fillColor: '#FF0000',
      //    fillOpacity: 0.35,
      //    map: map,
      //    center: {lat: center.lat, lng: center.lng},
      //    radius: <%=@radius%>
      //  });

        var center = (<%= raw @adj_center.to_json %>);
        var cityCircle = new google.maps.Circle({
          strokeColor: '#FC6F04',
          strokeOpacity: 0.8,
          strokeWeight: 2,
          fillColor: '#FFC836',
          fillOpacity: 0.35,
          map: map,
          center: {lat: center.lat, lng: center.lng},
          radius: <%=@radius%>
        });
      }
      else {
        map.setZoom(14);
        console.log('lat:' + ''  + markers[0].lat)
        map.panTo({lat: markers[0].lat, lng: markers[0].lng})
      };

      // function get hangout status when true/ set interval/ ajax get /  circle


    });
  <% end %>
<% end %>

app/views/hangouts/_form.html.erb
<div class="container center-align vertical-align form_wrapper z-depth-4">
<div class="tag-line-home white-text">
<h5><%=t('.titleh5')%></h5>
</div>
<div class="row form_wrapper_bottom_margin">
  <div class="col s12">

    <%= simple_form_for(@hangout)do |f| %>
      <% flash[:alert] = f.error_notification %>
      <%= f.input :title, label: false, placeholder: t('.placeholder_title'), error: false %>
      <div class="row">
        <div class="col s4 center-align vertical-align">
        <div class="face-dropdown"><p><%=t('.placeholder_category')%></p></div>
        </div>
        <div class="col s8">
        <%= f.input :category, label: false, collection: [:Food, :Drinks, :Coffee], autofocus: false, error: false %>
        </div>
      </div>
      <%= f.input :date, as: :string, label: false,  placeholder: t('.placeholder_date'), input_html: {
          class: '', value: @hangout.date.nil? ? "" : @hangout.date.strftime("%d/%m/%Y %H:%M")}%>
      <div class="checkbox-force">
        <div class=""><%=f.input :optimize_location, as: :boolean, boolean_style: :inline, label:t('.placeholder_boolean_html'), input_html: {checked: "checked"} %></div>
        <div id="info-check" class="tooltipped checkbox-force-item" data-position="bottom" data-delay="50" data-tooltip="<%=t('.tooltip')%>"><i class="grey-text tiny material-icons">help</i>
        </div>
      </div>

      <div id="force_zone_page" class="location_unforced">
        <p class="grey-text"><%= t('.explanation')%> </p>
        <div id="map" style="width:100%;height:200px; position: relative"></div>
      </div>
      <%= f.input :center_address, label: false, input_html: {class: 'location_unforced truncate'}%>
      <%= f.input :latitude, label: false, input_html: {class: 'location_unforced'} %>
      <%= f.input :longitude, label: false, input_html: {class: 'location_unforced'} %>


      <%= f.button :submit, class: "btn btn-primary"%>
        <p class="center-align blue-grey-text text-lighten-2" id="home-face-text">Powered by Facebook Connect</p>
    <% end %>

    </div>

    <div id="wrap">
      <div class="location_unforced">
        <input type="text" id="date"/>
        <input type="text" id="time"/>
      </div>
      <div id="outlet"></div>
    </div>


  <% content_for :after_js do %>
    <script>
    $(document).ready(function() {

    // select all on click
    $(document).on('click','input[type=text]',function(){ this.select(); });

      var datepicker = $('#date').pickadate({
              container: '#outlet',
              onSet: function(item) {
                  if ( 'select' in item ) setTimeout( timepicker.open, 0 )
              }
          }).pickadate('picker')

      var timepicker = $('#time').pickatime({
              container: '#outlet',
              onRender: function() {
                  $('<button>back to date</button>').
                      on('click', function() {
                          timepicker.close()
                          datepicker.open()
                      }).prependTo( this.$root.find('.picker__box') )
              },
              onSet: function(item) {
                  if ( 'select' in item ) setTimeout( function() {
                      $hangout_date.
                          off('focus').
                          val( datepicker.get() + ' @ ' + timepicker.get() ).
                          focus().
                          on('focus', datepicker.open)
                  }, 0 )
              }
          }).pickatime('picker')

      var $hangout_date = $('#hangout_date').
        on('focus', datepicker.open).
        on('click', function(event) { event.stopPropagation(); datepicker.open() })
      });
    $(document).ready(function() {
      $('select').material_select();
    });
    </script>
  <% end %>

  </div>
</div>
</div>

app/views/hangouts/_invitation.html.erb
<div class="header center-align vertical-align">
  <%= image_tag @hangout.user.facebook_picture_url, class: 'circle'%>
    <% if current_user == @hangout.user %>
      <h4 class="white-text"> <%= t('.host_message', host_name: @hangout.user.first_name) %></h4>
    <% else %>
      <h4 class="white-text"> <%= t('.message', host_name: @hangout.user.first_name ) %></h4>
    <% end %>
</div>
<div class="container">
 <div class="row">
   <div class="col s12">
       <h1 class="center-align"><%= @hangout.title%></h1>
   </div>
 </div>
 <div class="row">
   <div class="col s6 l3 offset-l3 center-align">
     <i class="material-icons">date_range</i></br>
      <h5 class="orange-text orange-accent-4"><%= l @hangout.date, format: :day %></h4>
   </div>
   <div class="col s6 l3 center-align">
     <i class="material-icons">access_time</i></br>
      <h5 class="orange-text orange-accent-4"><%= l @hangout.date, format: :hour %></h4>
   </div>
 </div>
 <div class="row">

  <div class="col s12 center-align">
    <% if current_user == @hangout.user %>
      <h5><%= t('.host_question', host_name: @hangout.user.first_name) %></h5>
        <%= link_to new_hangout_confirmation_path(@hangout), class: 'btn grey lighten-1 btn-large' do  %>
        <%= t('.set_location') %>
      <% end %>
    <% else %>
      <div class="col s12 center-align">
        <h5><%= t('.where') %></h5>
        <p><%= t('.concept_explanation_html', link: link_to( t('.explanation_link_html'), root_path)) %></p>
      </div>
      <h5><%= t('.question') %></h5>
        <%= link_to new_hangout_confirmation_path(@hangout), class: 'btn green btn-large' do  %>
        <i class="material-icons">check</i>
      <% end %>
      <%= link_to root_path, class: 'btn red btn-large' do  %>
        <i class="material-icons">close</i>
      <% end %>
    <% end %>
   </div>

  <div class="col s12 center-align">
  <br>
  <br>
    <%= link_to new_hangout_confirmation_path(@hangout), class:'facebook-btn facebook-btn-convite z-depth-2' do %>
      <i class="fa fa-facebook-official fa-2x" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;Log in With Facebook
    <% end %>
    <br><br>
  </div>
 </div>
</div>

app/views/hangouts/_past.html.erb
<div class="header center-align">
   <%= image_tag @hangout.user.facebook_picture_url, class: 'circle z-depth-2'%>
     <h4 class="white-text"><%=@hangout.title%></h4>
     <p class="white-text"><%= l @hangout.date, format: :short %></p>
 </div>
 <div class="status-wrapper red">
   <p class="white-text center-align"><%= t('.status') %></p>
 </div>
 <div class="container">
   <div class="row padded-top-1">
     <div class="col s12 m6 l8  offset-m3 offset-l2 center-align">
       <h1><i class="large material-icons">event_busy</i></h1>
       <h5><%= t('.content', host_name:@hangout.user.first_name, hangout_title: @hangout.title) %></h5>
         <p><%= l @hangout.date, format: :short %></p>
     </div>
   </div>
     <div class="row padded-top-1">
       <div class="col s12 m6 l8  offset-m3 offset-l2 center-align">
         <%= link_to t('.content-new'), root_path, class:'btn' %>
       </div>
    </div>
 </div>

app/views/hangouts/_vote_option.html.erb
<div class="header center-align">
  <%= image_tag @hangout.user.facebook_picture_url, class: 'circle z-depth-2'%>
    <h4 class="white-text"><%=@hangout.title%></h4>
    <p class="white-text"><%= l @hangout.date, format: :short %></p>
</div>


<% if has_voted? %>
<!-- status bar -->
<div class="status-wrapper green">
  <p class="white-text center-align"><%= t('.status-voted', default: 'Thanks for your vote! Wait for the votation to finish') %></p>
</div>
<!-- Only for hangout owner -->
<div class="container center-align">
<% if @hangout.user == current_user %>
  <p><%=t('.nb_conf') + ": #{@nb_conf}"%></p>
  <p><%=t('.nb_vote') + ": #{@nb_vote}"%></p>

  <div class="final-vote">
    <%= button_to t('.button_final_vote'), close_vote_hangout_path(@hangout), method: :patch, class: "btn  z-depth-1" %>
  </div>
  </div>
<% end %>

<!-- User choice -->
<div class="container">
  <h4 class="center-align padded-top-1"><%= t('.has_voted')%></h4>
  <!-- <h1><%= voted_place.name %></h1> -->
  <!-- <h2 class="center-align"><%= t('.wait')%></h2> -->
  <div class="row place-wrapper z-depth-1">
    <div class="content">
      <h5><%= link_to voted_place.name, voted_place.fsq_url, target: 'blank'%></h5>
      <h6><%= voted_place.address %></h6>
      <ul class="list-inline rating_wrapper">
        <li class="box-rating white-text"><%= voted_place.rating %>/10</li>
      </ul>
    </div>
    <div class="">
      <%= image_tag voted_place.photo_url %>
    </div>
  </div>
</div>

<% else %>
<!-- status bar -->
<div class="status-wrapper orange-accent-2">
  <p class="white-text center-align"><%= t('.status', default: 'Voting on! Choose your favorite!') %></p>
</div>

<!-- List of places -->
<div class="container">
  <div class="row">
    <div class="col s12 m6 offset-m3 center-align">
      <p>
        <%= t('.list', category: t('simple_form.options.hangout.category.'+ @hangout.category ))%>
      </p>
      <%= image_tag('poweredbyfoursquare300.png', class: 'fsq-logo')%>
    </div>
  </div>
</div>
  <div class="container">
    <% place_list.first(5).each do |option|%>
    <div class="row place-wrapper z-depth-1">
      <div class="content">
        <h5><%= link_to option.place.name, option.place.fsq_url, target: 'blank'%></h5>
        <h6><%= option.place.address %></h6>
        <ul class="list-inline rating_wrapper">
          <li class="box-rating white-text"><%= option.place.rating %>/10</li>
          <%= button_to( submit_vote_hangout_path(@hangout), method: :patch, params: {place_id: option.place_id}, class: "btn-vote-card z-depth-0") do %>
          Vote
          <% end %>
        </ul>
      </div>
      <div class="">
        <%= image_tag option.place.photo_url %>
      </div>
    </div>

<% end %>
  </div>
<% end %>

app/views/hangouts/edit.html.erb
<div class="background-home" style="background-image: url('<%= image_path("background.png")%>')">
</div>

<%= render 'form' %>

app/views/hangouts/index.html.erb
index!!

app/views/hangouts/new.html.erb
<div class="background-home" style="background-image: url('<%= image_path("background.png")%>')">
</div>
<%= render 'form'%>

app/views/hangouts/share.html.erb
<div class="header center-align">
  <%= image_tag @hangout.user.facebook_picture_url, class: 'circle z-depth-2'%>
    <h4 class="white-text"><%=@hangout.title%></h4>
    <p class="white-text"><%= l @hangout.date, format: :short %></p>
</div>
<div class="container">
  <div class="row">
    <div class="col s12 m6 l8  offset-m3 offset-l2 center-align">
      <h4 class="padded-top"><%= t('.message') %></h4>
    </div>
  </div>
  <div class="row">
    <div class="col s12 m6 l8  offset-m3 offset-l2 center-align">
      <div id="share" class=""></div>
      <button class="btn-small blue " onclick="Materialize.toast('Copied', 2000)" data-clipboard-text='<%= hangout_url(@hangout).html_safe %>'>
        <i class="fa fa-files-o" aria-hidden="true"></i> Copy url
      </button> <%= link_to "View Hangout", hangout_path(@hangout), class: "btn-small " %>
    </div>
      <div class="col s12 m6 l8  offset-m3 offset-l2 center-align">
    </div>
  </div>
</div>



<% content_for :after_js do %>
  <script>
    $(document).ready(function(){
      $("#share").jsSocials({
        url: "<%= hangout_url(@hangout) %>",
        text: " <%= @hangout.user.first_name %> convida você para o hangout <%= @hangout.title%>",
        title: "<%= @hangout.user.first_name %> convida você para o hangout <%= @hangout.title%>",
        shareIn : "blank",
        showLabel: true,
        showCount: false,
        shares: ["email", "messenger","whatsapp"]
      });
    });
  </script>
<% end %>

app/views/hangouts/show.html.erb
<%= render @render %>